# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: DAVODA_API_Util deploy

on:
    push:
        branches:
            - master

jobs:
    test-and-release:
        name: release
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 14

            - name: Install dependencies
              run: yarn

            - name: build
              run: yarn build

            - name: ZIP build
              run: zip -r dist.zip dist
            
            - name: Release
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                NPM_TOKEN: ${{ secrets.GH_TOKEN }}
              run:
                yarn semantic-release
